app:
  # 数据源配置信息
  dao:
    dataSource:
      url: jdbc:postgresql://10.1.1.147:5432/ksh_sys?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
      driverClass: org.postgresql.Driver
      username: postgres
      password: 123456
      sql-script-encoding: utf-8
    mybatis:
      dialect: postgresql
      aliasPackage: com.fosung.ksh.sys.dao

ksh:

  # 简项库地址配置
  sys:
    urls:
      simpleData: http://lzksh.fosung.com:98/simpledata

#redis配置地址
spring:
  redis:
    database: 1
    port: 6379
    host: 10.1.1.147
    password: 123456


#服务注册地址
eureka:
  instance:
    prefer-ip-address: true
    ip-address: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# 开启饥饿加载
ribbon:
  eager-load:
    enabled: true
  ConnectTimeout: 10000
  ReadTimeout: 60000
  MaxAutoRetries: 0 #对 第一次 请求 的 服务 的 重试 次数
  MaxAutoRetriesNextServer: 0 #要 重试 的 下一个 服务 的 最大 数量（ 不包括


logging:
  level:
    root: info
