#redis配置地址
spring:
  redis:
    database: 1
    port: 6379
    host: 10.1.1.147
    password: 123456

  zipkin:
    base-url: http://192.168.103.188:8081
#服务注册地址
eureka:
  instance:
    prefer-ip-address: true
    ip-address: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
